### GET запрос на получения Challenges по id пользователя
GET http://127.0.0.1:8000/api/challenges?athlete=2

### GET запрос на получения Challenges всех записей
GET http://127.0.0.1:8000/api/challenges/