### GET запрос на получения забегов
GET http://127.0.0.1:8000/api/runs/

### GET запрос на получения забегов с пагинацией
GET http://127.0.0.1:8000/api/runs/
    ?page=3&size=2

### Запрос на добавление комментария к забегу для конкретного пользователя
POST http://127.0.0.1:8000/api/runs/
Content-Type: application/json

{
  "comment": "Новый забег4",
  "athlete": 2
}

### GET запрос на получения забегов
POST http://127.0.0.1:8000/api/runs/30/start/


### GET запрос на получения забегов
POST http://127.0.0.1:8000/api/runs/30/stop/