### GET request to first endpoint
GET http://127.0.0.1:8000/api/company_details/


### GET запрос на получения тренеров и атлетов по параметрам в get запросе
GET http://127.0.0.1:8000/api/users/
    ?type=athlete

### GET запрос для поиска пользователя по полю search
GET http://127.0.0.1:8000/api/users/
    ?search=Юля


### GET запрос на получения забегов
GET http://127.0.0.1:8000/api/runs/

### GET запрос на получения забегов с пагинацией
GET http://127.0.0.1:8000/api/runs/
    ?page=3&size=2

### Запрос на добавление комментария к забегу для конкретного пользователя
POST http://127.0.0.1:8000/api/runs/
Content-Type: application/json

{
  "comment": "Удачный забег и отправка запроса для проверки API у Юлии через APIView1",
  "athlete": 2
}

### GET запрос на получения забегов
POST http://127.0.0.1:8000/api/runs/25/start/


### GET запрос на получения забегов
POST http://127.0.0.1:8000/api/runs/25/stop/

### GET запрос на получения записей атлетов
GET http://127.0.0.1:8000/api/athlete_info/1/

### PUT запрос на изменение записей атлетов
PUT http://127.0.0.1:8000/api/athlete_info/1/
Content-Type: application/json

{
  "goals": "Новая цель3",
  "weight": 45
}