### GET запрос на получения всех тренеров и атлетов без параметров
GET http://127.0.0.1:8000/api/users/

### GET запрос получения данных по конкретному пользователю
GET http://127.0.0.1:8000/api/users/4/

### GET запрос на получения тренеров и атлетов по параметрам в get запросе
GET http://127.0.0.1:8000/api/users/
    ?type=athlete

### GET запрос для поиска пользователя по полю search
GET http://127.0.0.1:8000/api/users/
    ?search=Юля

###