### GET запрос на получения тренеров и атлетов по параметрам в get запросе
GET http://127.0.0.1:8000/api/users/
    ?type=athlete

### GET запрос для поиска пользователя по полю search
GET http://127.0.0.1:8000/api/users/
    ?search=Юля

###