# Generated by Django 5.2 on 2025-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0003_alter_run_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="run",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "init"),
                    ("in_progress", "in_progress"),
                    ("finished", "finished"),
                ],
                default="init",
                max_length=20,
            ),
        ),
    ]
