# Generated by Django 5.2 on 2025-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0005_athleteinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athleteinfo",
            name="goals",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="athleteinfo",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
