# Generated by Django 5.2 on 2025-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0007_rename_user_id_athleteinfo_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="athleteinfo",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="athleteinfo",
            name="goals",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
