# Generated by Django 5.2 on 2025-09-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0009_challenge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
