# Generated by Django 5.2 on 2025-09-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0010_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="app_run.run",
            ),
        ),
    ]
