# Generated by Django 5.2 on 2025-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0011_alter_position_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="distance",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
