# Generated by Django 5.2 on 2025-09-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0012_run_distance"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectibleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("uid", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("pictures", models.URLField(max_length=500)),
                ("value", models.IntegerField()),
            ],
        ),
    ]
