# Generated by Django 5.2 on 2025-09-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0013_collectibleitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectibleitem",
            old_name="pictures",
            new_name="picture",
        ),
    ]
