# Generated by Django 5.2 on 2025-09-12 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0014_rename_pictures_collectibleitem_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectibleitem",
            name="athlete",
            field=models.ManyToManyField(
                related_name="athlete", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
