# Generated by Django 5.2 on 2025-09-14 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0015_collectibleitem_athlete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectibleitem",
            name="athlete",
            field=models.ManyToManyField(
                related_name="collectible_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="collectibleitem",
            name="latitude",
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name="collectibleitem",
            name="longitude",
            field=models.FloatField(db_index=True),
        ),
    ]
