# Generated by Django 5.2 on 2025-09-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0016_alter_collectibleitem_athlete_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectibleitem",
            old_name="athlete",
            new_name="items",
        ),
    ]
