# Generated by Django 5.2 on 2025-09-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0017_rename_athlete_collectibleitem_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectibleitem",
            old_name="items",
            new_name="athlete",
        ),
    ]
