# Generated by Django 5.2 on 2025-09-14 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0018_rename_items_collectibleitem_athlete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectibleitem",
            name="athlete",
            field=models.ManyToManyField(
                related_name="items", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
