# Generated by Django 5.2 on 2025-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0019_alter_collectibleitem_athlete"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="date_time",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="run",
            name="run_time_seconds",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
