# Generated by Django 5.2 on 2025-09-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0020_position_date_time_run_run_time_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="date_time",
            field=models.CharField(default=""),
        ),
    ]
