# Generated by Django 5.2 on 2025-09-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0021_alter_position_date_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="date_time",
        ),
    ]
