# Generated by Django 5.2 on 2025-09-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0022_alter_position_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="date_time",
            field=models.CharField(blank=True, default="0", null=True),
        ),
    ]
