# Generated by Django 5.2 on 2025-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0024_alter_run_athlete"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="distance",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="position",
            name="speed",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
