# Generated by Django 5.2 on 2025-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0025_alter_position_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="date_time",
            field=models.DateTimeField(
                blank=True, help_text="Формат: YYYY-MM-DDTHH:MM:SSZ", null=True
            ),
        ),
    ]
