# Generated by Django 5.2 on 2025-09-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0025_position_distance_position_speed"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="speed",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
