# Generated by Django 5.2 on 2025-10-08 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0026_run_speed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "athlete",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="athlete_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Атлет",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
                "unique_together": {("athlete", "coach")},
            },
        ),
    ]
