# Generated by Django 5.2 on 2025-10-09 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_run", "0027_subscribe"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="subscribe",
            table="subscribe",
        ),
    ]
